spanish = {
    language: "spanish",
    whatistuenti: "¿Qué es Tuerti?",
    whatistuentidesc: "Tuerti es una red social privada usada por millones de personas para comunicarse y compartir cada día.",
    social: "Social",
    socialdesc: "Conéctate, comparte y comunícate con tus amigos, compañeros de trabajo y familia.",
    local: "Local",
    localdesc: "Explora y júntate con los negocios locales y las marcas que realmente te importan.",
    mobile: "Móvil",
    mobiledesc: "Instala Tuerti en tu móvil en tiempo real, estés donde estés.",
    rememberme: "Recuérdame",
    forgotpassword: "¿Has olvidado tu contraseña?",
    register1: "¿Quieres una cuenta?",
    register2: "Regístrate",
    password: "Contraseña",
    about: "Acerca de",
    help: "Ayuda",
    privacy: "Política de Privacidad",
    legal: "Legal",
    register: "Registro",
    username: "Nombre de usuario",
    name: "Nombre",
    surnames: "Apellidos",
    gender: "Género",
    birthday: "Cumpleaños",
    country: "País",
    city: "Ciudad",
    occupation: "Estoy:",
    school: "En el colegio",
    college: "En la universidad",
    working: "Trabajando",
    universityquestion: "¿Fuiste a la universidad?",
    yes: "Si",
    no: "No",
    passwordconfirm: "Confirma la contraseña",
    submit: "Enviar",
    male: "Hombre",
    female: "Mujer",
    minage: "La edad mínima es 14.",
    reqfield: "Todos los campos son obligatorios",
    terms1: "Aceptas las ",
    terms2: "Condiciones de uso",
    terms3: " y la ",
    terms4: "Política de privacidad",
    terms5: " de Tuerti y que Tuerti te envíe comunicaciones, incluso por vía electrónica.",
    home: "Inicio",
    profile: "Perfil",
    messages: "Mensajes",
    people: "Gente",
    search: "Buscar...",
    uploadphotos: "Subir fotos",
    myaccount: "Mi cuenta",
    settings: "Preferencias",
    logout: "Cerrar sesión",
    visits: "visitas a tu perfil",
    calendar: "Calendario",
    createevent: "Crear evento",
    today: "Hoy",
    tomorrow: "Mañana",
    sevendays: "Próximos 7 días",
    seall: "Ver todos",
    noevents: "No tienes ningún evento.",
    info: "Información",
    edit: "Editar",
    date: "Fecha",
    time: "Hora",
    place: "Lugar",
    direction: "Dirección",
    desc: "Descripción",
    eventwall: "Tablón del evento",
    writehere: "Escribe aquí...",
    noposts: "Este tablón está vacío, se el primero en dejar un comentario.",
    hours: " Horas",
    until: "Hasta las ",
    allday: "Todo el día",
    webpage: "Página web",
    phone: "Teléfono",
    participants: "Participantes",
    invitefriends: "Invitar amigos",
    notifications: "Notificaciones",
    assistance: "Asistencia",
    maybe: "Quizás",
    willgo: "Van",
    maybego: "Quizás van",
    noresponse: "Aún no contestaron",
    assistants: "Personas que van a asistir",
    editevent: "Editar evento",
    changeimage: "Cambiar imagen",
    generalinfo: "Información general",
    eventtitle: "Título del evento",
    dateandhour: "Fecha y hora",
    addinfo: "Información adicional",
    privacy: "Privacidad",
    publicnotif: "Todos pueden enviar invitaciones a este evento",
    privatenotif: "Solo el creador puede enviar invitaciones a este evento",
    cancel: "Cancelar",
    eventdel: "Eliminar evento",
    areyousure: "¿Estás seguro?",
    createdby: "Creado por",
    personal: "Personal",
    age: "Edad",
    yearsold: "años",
    moredetails: "Más detalles",
    contact: "Contacto",
    registered: "Registrado",
    lastvisit: "Ultima visita",
    online: "En línea",
    friend: "Amigo",
    myalbums: "Mis álbumes de fotos",
    editprofile: "Editar perfil",
    seealbums: "Ver álbumes de fotos",
    privatemessage: "Mensaje privado",
    petitionsent: "Petición enviada",
    wanttoadd: "Esta persona quiere agregarte como amigo",
    accept: "Aceptar",
    deny: "Rechazar",
    addfriend: "Agregar como amig@",
    updatestatus: "Actualiza tu estado",
    lastupdate: "Ultima actualización",
    personalspace: "Espacio personal",
    emptyblog: "Tu blog está vacío",
    createentry: "Crea tu primera entrada de blog",
    title: "Título",
    entry: "Entrada",
    close: "Cerrar",
    video: "Vídeo",
    add: "Añadir",
    wall: "Tablón",
    show: "Mostrar",
    all: "Todo",
    statuses: "Estados",
    comments: "Comentarios",
    removefriend: "Borrar amigo",
    blockuser: "Bloquear usuario",
    reportuser: "Denunciar usuario",
    albums: "Albumes",
    photos: "Fotos",
    commonfriends: "Amigos en Común",
    nocommons: "No tenéis ningún amigo en común",
    friends: "Amigos",
    nofriendsyetown: "Aún no has agregado a ningún amigo",
    nofriendsyet: "Aún no ha agregado a nigún amigo",
    hours: "horas",
    hour: "hora",
    minutes: "minutos",
    minute: "minuto",
    rightnow: "Recientemente",
    and: "y",
    hace: "hace ",
    ago: "",
    image: "Imagen",
    text: "Texto"
};
english = {
    language: "english",
    whatistuenti: "What is Tuerti?",
    whatistuentidesc: "Tuerti is a private social platform used by millions of people to communicate and share every day.",
    social: "Social",
    socialdesc: "Connect, share and communicate with your friends, co-workers and family.",
    local: "Local",
    localdesc: "Explore and engage with local businesses and brands that you really care about.",
    mobile: "Mobile",
    mobiledesc: "Get Tuerti on your mobile phone in real time, wherever you are.",
    rememberme: "Remember me",
    forgotpassword: "Forgot your password?",
    register1: "Want an account?",
    register2: "Register",
    password: "Password",
    about: "About",
    help: "Help",
    privacy: "Privacy Policy",
    legal: "Legal",
    register: "Register",
    username: "Username",
    name: "Name",
    surnames: "Surname",
    gender: "Gender",
    birthday: "Birthday",
    country: "Country",
    city: "City",
    occupation: "I'm currently:",
    school: "At school",
    college: "At college",
    working: "Working",
    universityquestion: "Did you go to college?",
    yes: "Yes",
    no: "No",
    passwordconfirm: "Confirm password",
    submit: "Submit",
    male: "Male",
    female: "Female",
    minage: "The minimum age is 14.",
    reqfield: "Every field is required",
    terms1: "You accept Tuerti's ",
    terms2: "Terms of Use ",
    terms3: "and ",
    terms4: "Privacy Policy",
    terms5: " and that Tuerti will send you communications, even electronically.",
    home: "Home",
    profile: "Profile",
    messages: "Messages",
    people: "People",
    search: "Search...",
    uploadphotos: "Upload photos",
    myaccount: "My account",
    settings: "Settings",
    logout: "Logout",
    visits: "visits to your profile",
    calendar: "Calendar",
    createevent: "Create event",
    today: "Today",
    tomorrow: "Tomorrow",
    sevendays: "Next 7 days",
    seall: "See all",
    noevents: "You don't have any events.",
    info: "Information",
    edit: "Edit",
    date: "Date",
    time: "Time",
    place: "Place",
    direction: "Direction",
    desc: "Description",
    eventwall: "Event Wall",
    writehere: "Write here...",
    noposts: "This wall is empty, be the first one to write a comment.",
    hours: " Hours",
    until: "Until ",
    allday: "The whole day",
    webpage: "Webpage",
    phone: "Telephone",
    participants: "Participants",
    invitefriends: "Invite friends",
    notifications: "Notifications",
    assistance: "Assistence",
    maybe: "Maybe",
    willgo: "Will go",
    maybego: "May go",
    noresponse: "No answer yet",
    assistants: "People who will assist",
    editevent: "Edit event",
    changeimage: "Change image",
    generalinfo: "General information",
    eventtitle: "Event title",
    dateandhour: "Date and hour",
    addinfo: "Additional Information",
    privacy: "Privacy",
    publicnotif: "Anyone can send invitations for this event",
    privatenotif: "Only the owner can send invitations for this event",
    cancel: "Cancel",
    eventdel: "Delete event",
    areyousure: "Are you sure?",
    createdby: "Created by",
    personal: "Personal",
    age: "Age",
    yearsold: "years old",
    moredetails: "More details",
    contact: "Contact",
    registered: "Registered on",
    lastvisit: "Last activity",
    online: "Online",
    friend: "Friend",
    myalbums: "My photo albums",
    editprofile: "Edit profile",
    seealbums: "See photo albums",
    privatemessage: "Private message",
    petitionsent: "Petition sent",
    wanttoadd: "This person wants to be your friend",
    accept: "Accept",
    deny: "Deny",
    addfriend: "Add as friend",
    updatestatus: "Update your status",
    lastupdate: "Last update",
    personalspace: "Personal space",
    emptyblog: "Your blog is empty",
    createentry: "Create your first blog entry",
    title: "Title",
    entry: "Entry",
    close: "Close",
    video: "Video",
    add: "Add",
    wall: "Wall",
    show: "Show",
    all: "All",
    statuses: "Statuses",
    comments: "Comments",
    removefriend: "Remove friend",
    blockuser: "Block user",
    reportuser: "Report user",
    albums: "Albums",
    photos: "Photos",
    commonfriends: "Common friends",
    nocommons: "You don't have any common friends",
    friends: "Friends",
    nofriendsyetown: "You still have not added any friend",
    nofriendsyet: "This person still have not added any friend",
    hours: "hours",
    hour: "hour",
    minutes: "minutes",
    minute: "minute",
    rightnow: "Recently",
    and: "and",
    hace: "",
    ago: " ago",
    image: "Imagen"
};

languages = { spanish, english };

module.exports = languages;